# Generated by DoScript Visual IDE v0.6.5

# Script Start
say "===Vexon Installer==="
global_variable = confirm
ask confirm "Would you like to install vexon?(y/n)"
if confirm == "y"
say "Installing..."
make folder "C:/Vexon"
download "https://github.com/TheServer-lab/vexon/releases/download/doscript-release/vexon-do.zip" to "C:/Vexon/vexon-do.zip"
unzip "C:/Vexon/vexon-do.zip" to "C:/Vexon"
path add "C:/Vexon/Get_Vexon"
delete "C:/Vexon/vexon-do.zip"
say "Installation complete!"
end_if
pause
